#!/bin/bash
docker run --restart always --name overlord -p 5000:80 -d nginx
# --restart		restart mode, always will restart regardless of the SIG status
# -d			as detach mode
# --name		name the container
# -p			map the port from host to container
