#!/bin/bash

docker run -d \
	--name lair \
	-p 8080:80 \
	--link spawning-pool \
	-e WORDPRESS_DB_HOST=spawning-pool:3306 \
	-e WORDPRESS_DB_USER=root \
	-e WORDPRESS_DB_PASSWORD=Kerrigan \
	-e WORDPRESS_DB_NAME=wordpress \
	-e WORDPRESS_TABLE_PREFIX=wp_ \
	wordpress


# need to
# mysql -h 127.0.0.1 -P 3306 -u root -p
# ALTER USER 'root'@'%'
#  IDENTIFIED WITH mysql_native_password
#  BY 'Kerrigan';
# if not started db with --default-authentication-plugin=mysql_native_password

# Reason :https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
# 'root'@'%' means root from any connection.
# in docker lair aka wordpress is connection from subnet not from localhost
