#!/bin/bash

docker-machine mount Char:/home/docker/ex19 00_how_to_docker/ex19

docker run -dit\
	--name Abathur \
	-v /home/docker/ex19:/root \
	-p 3000:3000 \
	python:2-slim

cp 00_how_to_docker/app.py 00_how_to_docker/ex19

docker exec \
	Abathur \
	pip install Flask

cp 00_how_to_docker/app.py /nfs/2018/s/seli/vogosphere/app.py

docker exec \
	-de FLASK_APP=/root/app.py \
	Abathur \
	flask run --host=0.0.0.0 --port 3000

# umount 00_how_to_docker/ex19


