#!/bin/bash

docker run -dit\
	--name Abathur \
	-v ~/:/root \
	-p 3000:3000 \
	python:2-slim

docker exec \
	Abathur \
	pip install Flask

cp 00_how_to_docker/app.py ~/app.py

docker exec \
	-de FLASK_APP=/root/app.py \
	Abathur \
	flask run --host=0.0.0.0 --port 3000
# rm ~/app.py


