#!/bin/bash

docker-machine ssh Char mkdir ex19
docker-machine mount Char:/home/docker/ex19 00_how_to_docker/ex19

docker run -dit\
	--name Abathur \
	-v /home/docker/ex19:/root \
	-p 3000:3000 \
	python:2-slim

cp 00_how_to_docker/app.py 00_how_to_docker/ex19

docker exec \
	Abathur \
	pip install Flask

docker exec \
	-de FLASK_APP=/root/app.py \
	Abathur \
	flask run --host=0.0.0.0 --port 3000

# brew install sshfs
# umount 00_how_to_docker/ex19


